services:

  flask:
    build: app
    container_name: flask
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_NAME=GraphApp
    expose:
      - 8000
    ports:
      - 8000:8000