app_version:
  version: "1.0.0"
  date: "2021-06-01"

title:
  city_key_enrollment_pie_chart_title: "Ciudadanos inscritos en la Tarjeta Ciudadana"
  bus_year_rides_pie_chart_title: "Viajes en bus anuales"
  bus_year_registered_rides_pie_chart_title: "Viajes en bus anuales de ciudadanos inscritos"
  bus_year_fisical_and_virtual_card_rides_pie_chart_title: "Viajes en bus anuales con tarjeta física o virtual"
  monthly_bus_rides_bar_chart_title: "Comparativa de viajes mensuales"
  annual_bus_rides_bar_chart_title: "Comparativa de viajes anuales"
  dayly_bus_rides_bar_chart_title: "Comparativa de viajes diarios"

  activities_pie_chart_title: "Actividades culturales, talleres y cursos"

label:
  enrolled: "Ciudadanos incritos"
  not_enrolled: "Ciudadanos no inscritos"

  total_bus_rides: "Total"
  in_year_bus_rides: "Año actual"

  in_year_not_registered_rides: "Usuarios no censados"
  in_year_registered_bus_rides: "Usuarios censados"

  fisical_card_bus_rides: "Tarjeta física"
  virtual_card_bus_rides: "Tarjeta virtual"
