app_version:
  version: "0.0.1"
  date: "18-10-2024"

title:
  city_key_enrollment_pie_chart_title: "Ciudadanos inscritos en la Tarjeta Ciudadana"
  city_key_yearly_enrollment_bar_chart_title: "Inscripciones mensuales durante el año en la Tarjeta Ciudadana"
  city_key_daily_enrollment_bar_chart_title: "Inscripciones diarias durante el mes en la Tarjeta Ciudadana"
  city_key_weekly_enrollment_bar_chart_title: "Inscripciones diarias durante la semana en la Tarjeta Ciudadana"
  city_key_dayly_enrollment_bar_chart_title: "Inscripciones del día en la Tarjeta Ciudadana"
  monthly_recharges_and_bonus_uses_bar_chart_title: "Usos de bonos y recargas mensuales"
  daily_by_month_recharges_and_bonus_uses_bar_chart_title: "Usos de bonos y recargas diarios durante el mes"
  weekly_recharges_and_bonus_uses_bar_chart_title: "Usos de bonos y recargas durante la semana"
  daily_recharges_and_bonus_uses_bar_chart_title: "Usos de bonos y recargas diarios"

  bus_year_rides_pie_chart_title: "Viajes en bus anuales"
  bus_year_registered_rides_pie_chart_title: "Viajes en bus anuales de ciudadanos inscritos"
  bus_year_fisical_and_virtual_card_rides_pie_chart_title: "Viajes en bus anuales con tarjeta física o virtual"
  monthly_bus_rides_bar_chart_title: "Comparativa de viajes mensuales"
  annual_bus_rides_bar_chart_title: "Comparativa de viajes anuales"
  dayly_bus_rides_bar_chart_title: "Comparativa de viajes diarios"
  daily_by_month_bus_rides_bar_chart_title: "Comparativa de viajes diarios durante el mes"
  weekly_bus_rides_bar_chart_title: "Comparativa de viajes durante la semana"

  activities_pie_chart_title: "Actividades culturales, talleres y cursos"

label:
  registered: "Ciudadanos empadronados"
  not_registered: "Ciudadanos no empadronados"

  total_bus_rides: "Total"
  in_year_bus_rides: "Año actual"

  in_year_not_registered_rides: "Usuarios no censados"
  in_year_registered_bus_rides: "Usuarios censados"

  fisical_card_bus_rides: "Tarjeta física"
  virtual_card_bus_rides: "Tarjeta virtual"
